### ISSUE TITLE
Outdated warning regarding number of solution files

### ISSUE THREAD

**Issue by stkent** [exercism/cli-www#29]
The "Basic Usage" section of this documentation page contains the following warning (my emphasis):

> You only need to submit the code you wrote to solve the exercise, not the test suite that you were given. **At the moment each exercise must be solved in a single file.**

Apparently this is [no longer true](https://github.com/exercism/xjava/issues/185#issuecomment-262931341). The copy and example invocation should be updated to reflect the fact that uploading multiple solution files is now supported.

**Comment by kytrinyx** [comment]
That's a good catch. We did fix this a while back.

**Comment by robphoenix** [comment]
I believe this PR https://github.com/exercism/cli-www/pull/30 closes this issue?

**Comment by kytrinyx** [comment]
Yepp, it sure does. Thanks!

**Comment by stevejb71** [comment]
Does the site need to be rebuilt. The old text is still there in http://cli.exercism.io

**Comment by kytrinyx** [comment]
@stevejb71 Uhm... that would be "yes". Sheesh :-) Thanks

**Comment by kytrinyx** [comment]
I'm having trouble deploying at the moment. I'll try again in an hour.

**Comment by kytrinyx** [comment]
This is now deployed.

**Comment by stevejb71** [comment]
LGTM ☺️
