### ISSUE TITLE
Why are completion scripts here?

### ISSUE THREAD

**Issue by QuLogic** [exercism/cli-www#34]
This is the website repo; it seems like a very hard-to-find place. Why not in the [`cli`](https://github.com/exercism/cli) repo?

**Comment by kytrinyx** [comment]
That's an excellent question. I'm not sure why we didn't think of putting them in the CLI repo.

Honestly we should probably add them to the archive that we distribute for the CLI release.

**Comment by QuLogic** [comment]
Not really fixed yet...

**Comment by kytrinyx** [comment]
I've moved this issue into the repository for the CLI where it will likely get more attention.

https://github.com/exercism/cli/issues/508
