### ISSUE TITLE
http://cli.exercism.io/exercism_completion.bash is down

### ISSUE THREAD

**Issue by maia13** [exercism/cli-www#37]
It says: Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by kytrinyx** [comment]
Thanks @maia13. I'll get this sorted out this weekend!

**Comment by kytrinyx** [comment]
Ok, I've gotten this _mostly_ sorted out, just waiting for DNS to propagate (supposedly I had a TTL of 1 hour, but it's been almost 4, so I'm thinking we might be looking at a 24 hour delay while the internet clears its throat).

I'll check back in tomorrow to see if it's _actually_ fixed!

**Comment by kytrinyx** [comment]
Alrighty—DNS propagation is complete, and cli.exercism.io is working!
